//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestsPortal.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestsPortal.WebSite.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        public static string AboutYourself {
            get {
                return ResourceManager.GetString("AboutYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество участников.
        /// </summary>
        public static string CompetitorsCount {
            get {
                return ResourceManager.GetString("CompetitorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время начала.
        /// </summary>
        public static string ContestBeginning {
            get {
                return ResourceManager.GetString("ContestBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий к соревнованию.
        /// </summary>
        public static string ContestCommentTitle {
            get {
                return ResourceManager.GetString("ContestCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время окончания.
        /// </summary>
        public static string ContestEnd {
            get {
                return ResourceManager.GetString("ContestEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомлять меня по почте заранее перед предстоящим контестом.
        /// </summary>
        public static string ContestNotificationsEnabled {
            get {
                return ResourceManager.GetString("ContestNotificationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип соревнования.
        /// </summary>
        public static string ContestPriorityName {
            get {
                return ResourceManager.GetString("ContestPriorityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная стадия - контест проводится и еще не завершен..
        /// </summary>
        public static string ContestStateActive {
            get {
                return ResourceManager.GetString("ContestStateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стадия ожидания - Создана запись в БД, но регистрация на контест еще не открыта.
        /// </summary>
        public static string ContestStateAwaiting {
            get {
                return ResourceManager.GetString("ContestStateAwaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контест завершен. Подведены итоги..
        /// </summary>
        public static string ContestStateCompleted {
            get {
                return ResourceManager.GetString("ContestStateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыта регистрация участников.
        /// </summary>
        public static string ContestStateRegistration {
            get {
                return ResourceManager.GetString("ContestStateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контест  уже завершился, проводится подведение итогов..
        /// </summary>
        public static string ContestStateResultEvaluation {
            get {
                return ResourceManager.GetString("ContestStateResultEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контест успешно создан и перенесен в список ожидающих.
        /// </summary>
        public static string ContestSuccessfullyAdded {
            get {
                return ResourceManager.GetString("ContestSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название соревнования.
        /// </summary>
        public static string ContestTitle {
            get {
                return ResourceManager.GetString("ContestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна проживания.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электроной почты.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-сайт.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название языка.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображаемое имя (Никнэйм).
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость задачи (баллы, 1-300).
        /// </summary>
        public static string TaskAward {
            get {
                return ResourceManager.GetString("TaskAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий к задаче.
        /// </summary>
        public static string TaskComment {
            get {
                return ResourceManager.GetString("TaskComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сложность задачи (1-20 баллов).
        /// </summary>
        public static string TaskComplexity {
            get {
                return ResourceManager.GetString("TaskComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст задачи.
        /// </summary>
        public static string TaskContent {
            get {
                return ResourceManager.GetString("TaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность задачи (1-300, мин.).
        /// </summary>
        public static string TaskDuration {
            get {
                return ResourceManager.GetString("TaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество задач (1-10).
        /// </summary>
        public static string TasksCount {
            get {
                return ResourceManager.GetString("TasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование задачи.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
