//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestsPortal.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestsPortal.WebSite.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать дату рождения.
        /// </summary>
        public static string BirhtdateIsRequired {
            get {
                return ResourceManager.GetString("BirhtdateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать дату начала контеста.
        /// </summary>
        public static string ContestBeginningRequired {
            get {
                return ResourceManager.GetString("ContestBeginningRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина комментария не должна превышать 300 символов.
        /// </summary>
        public static string ContestCommentMaxLength {
            get {
                return ResourceManager.GetString("ContestCommentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименования ограничено длиной  300 символов.
        /// </summary>
        public static string ContestTitleLength {
            get {
                return ResourceManager.GetString("ContestTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести наименование соревнования.
        /// </summary>
        public static string ContestTitleRequired {
            get {
                return ResourceManager.GetString("ContestTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать страну проживания.
        /// </summary>
        public static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email имеет некорректный формат.
        /// </summary>
        public static string EmailHasIncorrectFormat {
            get {
                return ResourceManager.GetString("EmailHasIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать адрес электронной почты.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен некорректный номер телефона.
        /// </summary>
        public static string IncorrectPhoneNumber {
            get {
                return ResourceManager.GetString("IncorrectPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин, Email либо пароль введены некорректно..
        /// </summary>
        public static string InvalidUserCredentials {
            get {
                return ResourceManager.GetString("InvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать никнейм.
        /// </summary>
        public static string NickNameIsRequired {
            get {
                return ResourceManager.GetString("NickNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже существует такой никнейм в системе.
        /// </summary>
        public static string NickNameIsUnique {
            get {
                return ResourceManager.GetString("NickNameIsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают.
        /// </summary>
        public static string PasswordConfDoesntFit {
            get {
                return ResourceManager.GetString("PasswordConfDoesntFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать пароль.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контест отсуствует в БД..
        /// </summary>
        public static string SuchContestIsAbsent {
            get {
                return ResourceManager.GetString("SuchContestIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cтоимость задачи ограничена диапазоном 1..300.
        /// </summary>
        public static string TaskAwardRange {
            get {
                return ResourceManager.GetString("TaskAwardRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать стоимость задачи.
        /// </summary>
        public static string TaskAwardRequired {
            get {
                return ResourceManager.GetString("TaskAwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина комментария ограничена 300 символами.
        /// </summary>
        public static string TaskCommentMaxLength {
            get {
                return ResourceManager.GetString("TaskCommentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать сложность задачи.
        /// </summary>
        public static string TaskComplexityRequired {
            get {
                return ResourceManager.GetString("TaskComplexityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сложность задачи ограничена диапазоном 1..20.
        /// </summary>
        public static string TaskComplextityRange {
            get {
                return ResourceManager.GetString("TaskComplextityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать содержание задачи.
        /// </summary>
        public static string TaskContentRequired {
            get {
                return ResourceManager.GetString("TaskContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность решения задачи ограничена диапазоном 0..5 часов.
        /// </summary>
        public static string TaskDurationRange {
            get {
                return ResourceManager.GetString("TaskDurationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать длительность задачи.
        /// </summary>
        public static string TaskDurationRequired {
            get {
                return ResourceManager.GetString("TaskDurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество задач должно быть как минимум 1 и не превышать 10..
        /// </summary>
        public static string TasksCountRange {
            get {
                return ResourceManager.GetString("TasksCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать количество решаемых задач.
        /// </summary>
        public static string TasksCountRequired {
            get {
                return ResourceManager.GetString("TasksCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название задачи не должно превышать длину в 200 символов.
        /// </summary>
        public static string TaskTitleMaxLength {
            get {
                return ResourceManager.GetString("TaskTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать название задачи.
        /// </summary>
        public static string TaskTitleRequired {
            get {
                return ResourceManager.GetString("TaskTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный Email уже существует в системе.
        /// </summary>
        public static string UniqueEmail {
            get {
                return ResourceManager.GetString("UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный Никнейм уже сущесвтует в системе.
        /// </summary>
        public static string UniqueNickName {
            get {
                return ResourceManager.GetString("UniqueNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный логин уже существует в системе.
        /// </summary>
        public static string UniqueUserName {
            get {
                return ResourceManager.GetString("UniqueUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать хэндл пользователя.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
    }
}
